const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  refreshToken: state => state.user.refreshToken,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  userInfo: state => state.user.userInfo,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  // libRouters: state => state.permission.libRouters,
  errorLogs: state => state.errorLog.logs,
  ipconfig: state => state.user.ipconfig,
  port: state => state.user.port,
  loginname: state => state.user.loginname,
  projectNum: state => state.app.projectNum,
  projectId: state => state.app.projectId,
  ifSearch: state => state.app.ifSearch
}
export default getters
